module.exports = {
  ANSWER_ONE_ID_USER: 'answerOwnIdUser',
  ERROR_ONE_ID: 'errorOneId',
  SUBJECT_ONE: 'SUBJECT_ONE',
  SUBJECT_ONE_TOTAL: 'SUBJECT_ONE_TOTAL',
  SUBJECT_ONE_COLLECTION: 'SUBJECT_ONE_COLLECTION',
};
